# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5440dc72779ea39f4c82be0f83d25403be0c97a97845cdb123518eeb7bbb178e29a75608872552a8ae153b1465b0ce01d705d29360a75245df682b1abc783ab6

test:
  secret_key_base: 8bc772d6c2b6b2ce8c70bbba84ae3922601cec40b38715b75e6ad39d56d8b4fd21a082a6f4776b132250db5b8e9934fe3b16cabd2a67e34f3b3b18c63c5585bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
